In [56]:
import numpy as np

In [73]:
lambida = 1

In [57]:
X = np.array([[2,1,2],[4,3,4],[1,1,2]])
print(X)

[[2 1 2]
 [4 3 4]
 [1 1 2]]


In [65]:
X_t = np.transpose(X)
print (X_t)

[[2 4 1]
 [1 3 1]
 [2 4 2]]


In [70]:
np.dot(X_t,X)

array([[21, 15, 22],
       [15, 11, 16],
       [22, 16, 24]])

In [74]:
np.identity(3) * lambida

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
print(np.dot(X_t,X) + np.identity(3) * lambida)

[[22. 15. 22.]
 [15. 12. 16.]
 [22. 16. 25.]]


In [76]:
A_inv = np.linalg.inv(np.dot(X_t,X) + np.identity(3) * lambida)
print(A_inv)

[[ 0.46315789 -0.24210526 -0.25263158]
 [-0.24210526  0.69473684 -0.23157895]
 [-0.25263158 -0.23157895  0.41052632]]


In [59]:
nSamples, nFeatures = X.shape
print(nSamples,nFeatures)

3 3


In [60]:
Xinv = np.linalg.inv(X)
print (Xinv)

[[ 1.   0.  -1. ]
 [-2.   1.  -0. ]
 [ 0.5 -0.5  1. ]]


In [61]:
np.dot(X, Xinv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append("..")
from utils import *
from linear_regression import *
from svm import *
from softmax import *
from features import *
from kernel import *

In [79]:
train_x, train_y, test_x, test_y = get_MNIST_data()

In [82]:
print('train_x, train_y, test_x, test_y',train_x.shape, train_y.shape, test_x.shape, test_y.shape)

train_x, train_y, test_x, test_y (60000, 784) (60000,) (10000, 784) (10000,)


In [1]:
np.e

NameError: name 'np' is not defined