In [2]:
import numpy as np

In [3]:
np.random.random([2,1])

array([[0.57636823],
       [0.29516979]])

In [4]:
np.random.random([5,6])

array([[0.87773032, 0.64675871, 0.715835  , 0.55390042, 0.86975697,
        0.63833038],
       [0.43281743, 0.25181249, 0.5106848 , 0.9093942 , 0.22891068,
        0.41805977],
       [0.06472111, 0.62789485, 0.4994568 , 0.82515945, 0.80564464,
        0.30429281],
       [0.51777938, 0.20716094, 0.1665118 , 0.05309417, 0.04435052,
        0.15210544],
       [0.05021843, 0.09313781, 0.38413944, 0.42521087, 0.83520091,
        0.37383122]])

In [39]:
x = np.array([[0.98430378, 0.70542949], [0.68332926, 0.73808061]])
x

array([[0.98430378, 0.70542949],
       [0.68332926, 0.73808061]])

In [29]:
# L2 norm of a matrix - Formula
y = np.sqrt(x[0]*x[0] + x[1]*x[1])
y

3.605551275463989

In [30]:
# L2 norm of a matrix - Function (Numpy)
z = np.linalg.norm(x)
z

3.605551275463989

In [31]:
w = np.sqrt(np.square(x[0]) + np.square(x[1]))
w

3.605551275463989

In [27]:
y == z == w

True